### ISSUE TITLE
mapboxgl is not defined error

### ISSUE THREAD

**Issue by jparish3** [PolymerVis/mapbox-gl#1]
The element does not render a map and generates the error message below. This is also the case on the webcomponents site(https://www.webcomponents.org/element/PolymerVis/mapbox-gl). The map does not display on the first page but works using the demo link (https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/index.html)

Uncaught ReferenceError: mapboxgl is not defined
    at HTMLElement._createMap (mapbox-gl.html:287)
    at HTMLElement.<anonymous> (mapbox-gl.html:270)
    at Debouncer.complete (polymer-mini.html:2085)
    at Debouncer.boundComplete (polymer-mini.html:2062)

**Comment by eterna2** [comment]
The error is because mapbox-gl.js is not loaded.

This is because the default location to the lib was wrongly set. Sorry for the problem.

However, I also discovered that mapbox-gl-js package in bower is very outdated (v0.11 where the latest is v0.32). So in mapbox-gl v1.0.1, I have removed the dependency to mapbox-gl-js in bower, and replace the default script location to mapbox's CDN. 

However, you can still overwrite the mapbox lib location via the `script-src` attribute.

```html
<mapbox-gl id="map"
  interactive
  map="{{map}}"
  script-src="https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js"
  map-style="mapbox://styles/mapbox/dark-v9"
  access-token="<MAPBOX_ACCESS_TOKEN>"
  latitude=1.3521
  longitude=103.8698
  zoom=16
  pitch=45
  bearing=0></mapbox-gl>
```

**Comment by jparish3** [comment]
Thanks for the version update; works well. I would like to load data from
iron-ajax calls using markers or other data visualization tools using the
mapbox element. Can you direct me to relevant documentation?

**Comment by eterna2** [comment]
Can u give me more details on what u want to do exactly?

This element is still a WIP, as I have not incorporated all of mapbox-gl API yet.

The latest release adds a new element `mapbox-gl-marker`, which is a direct map to mapboxgl.Marker - it essentially allows you to add markers to your map as long as you provide the lat and lng.

**Comment by jparish3** [comment]
Thanks. We currently use the Google Map element to display data returned
from iron-ajax calls with the marker or point-overlay elements. (I would
like to use a heatmap element, but am having trouble getting the data
configured. ) In order to query the data we extract map API components for
data binding. I tested one of the mapbox API components (see below) but did
get results
 I also tried the deck-gl choropleth but did not understand where the demo
javascript fits within an element. We have many spatial data needs and are
excited to use mapbox and its visualizations. Thanks for adding this to
Polymer

 _fillInCenter: function(event) {
      var center = this.map.getCenter();
      if (!center) {
        return;
      }
     this.$.center.value = this.map.getCenter();
   },

**Comment by eterna2** [comment]
@jparish3 
Hi, sorry for the slow response. Was very busy with work.

I have updated with a few more new components:
- `geojson-source`: component to load your geojson data.
- `mapbox-layer`: generic mapbox layer, currently only `fill`, `line`, and `circle` are available.
- `mapbox-heatmap-layer`: a heatmap created with multiple `mapbox-layer`.

You can look at the example at the webcomponent page:
https://www.webcomponents.org/element/PolymerVis/mapbox-gl

**Comment by jparish3** [comment]
Thanks for adding these highly valued components. I would like to use the
map element with data binding, but cannot seem to make the following API
calls from the element...would appreciate any advice. Thanks

*getBounds()*
Returns
LngLatBounds: The map's geographical bounds.

*getCenter()*
Returns
LngLat: The map's geographical centerpoint.

**Comment by eterna2** [comment]
```
<mapbox-gl map={{map}}></mapbox-gl>
```

the mapbox-gl element returns the map object. You can call any mapbox function directly. 

e.g.
```
map.getBounds();
```

If u want to have a constantly updated values, you can try getting these values inside the `mapbox-gl-move` event. Note: move is the on event that is watched by default. For the rest, you will need to add them into `events-to-watch` attributes.

```html
<mapbox-gl on-mapbox-gl-move="handleMove"></mapbox-gl>
```

```javascript
app.handleMove = function(e, info) {
  console.log(this.map.getBounds());
};
```
