### ISSUE TITLE
Mapbox control styles not applying

### ISSUE THREAD

**Issue by loppear** [PolymerVis/mapbox-gl#13]
I'm sure this is something simple on my part, but attempting to use the demo as a start I'm stumped by some interaction with the shadowdom that's not applying the mapbox css appropriately (obviously, `mapbox-control-container` / `mapbox-ctrl*`, but presumably all from mapbox-gl.css):

<img width="263" alt="mapbox-styles" src="https://user-images.githubusercontent.com/539208/32510210-be490902-c3bd-11e7-9010-f079c37ea29a.png">

```
    <link rel="import" href="bower_components/shadycss/apply-shim.html">
    <link rel="import" href="bower_components/mapbox-gl/mapbox-gl.html">
```

```
    <custom-style>
        <style is="custom-style">
         mapbox-gl {
             height: 500px;
             width: 100%;
         }
        </style>
    </custom-style>
    <dom-bind>
            <div class="container">
                <div class="row">
                    <mapbox-gl
                        interactive
                        map="{{map}}"
                        access-token="[[my-access-token]]"
                        map-style-url="mapbox://styles/mapbox/streets-v10"
                    ></mapbox-gl>
                </div>
            </div>
    </dom-bind>
```

I've tried explicitly setting `css-src` and directly `link`ing the mapbox css - in either case, the css file is loading from api.mapbox.com and the rendered elements for the map and controls appear fine, but styles are not applied within the shadow root. (Tested on FF and Chrome)

Mapbox-gl installed from bower, v2.0.6
Polymer installed as dep via bower, v2.2.0

**Comment by eterna2** [comment]
Hi I just pushed a new update. 

Instead of importing the CSS, I create the style element dynamically inside the shadow-dom. It works now.

**Comment by eterna2** [comment]
You can see an example of this at https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/centered.html
