### ISSUE TITLE
Dinamically remove markers inside dom-repeat

### ISSUE THREAD

**Issue by ralexrdz** [PolymerVis/mapbox-gl#26]
I'm binding an array to a `dom-repeat` to show markers in a map
``` js
markers: {
  type: Array,
  value: [{lat: 19.4, lng: -99.15, msg: 'Marker 1'}, {lat: 19.3, lng: -99.15, msg: 'Marker 2'}] 
```
``` js
this.set('markers', this.markers.slice(0,1)) // or what ever
```
when the array changes, specifically remove some elements, the markers stay in the map.

Any ideas?
How could I achieve this?

**Comment by ralexrdz** [comment]
for a very strange reason If change your `mapbox-gl-marker.html` file in line 173
```js
if (this.x) {
  this.x.remove();
}
```
and in line 214 
```js
let mapboxMarker = new mapboxgl.Marker(ele, {offset: [offsetLeft, offsetTop]})
                          .setLngLat([this.longitude, this.latitude])
                          .addTo(map)
this.set('x',mapboxMarker)
return mapboxMarker;
```

it do binds and remove the Markers

My main problem is that marker property is `undefined`. I don't know why, I've tried debbug it and have no clue why this happens. I've even removed the `readOnly: true` and nothing

I'll open other issue [#27]

**Comment by eterna2** [comment]
Let me have a look.

**Comment by eterna2** [comment]
@ralexrdz I made a typo mistake. I forgot to return the marker object when creating it. It should work in the next release. 

Once I fix the other few bugs, I will release the next version.
