### ISSUE TITLE
marker property undefined

### ISSUE THREAD

**Issue by ralexrdz** [PolymerVis/mapbox-gl#27]
When selecting `<mapbox-gl-marker>`, marker property give me `undefined`

Even when its computed with the `_createMarker` method, I can not access Mapbox Marker Object of the element

``` js
console.log(this) // <mapbox-gl-marker latitude="1.3523" longitude="103.8655" width="128" height="12"></mapbox-gl-marker>
console.log(this.marker) // undefined
```

**Comment by eterna2** [comment]
Fixed this together with #26 
Both derives from the same typo mistake I made.
