### ISSUE TITLE
Blank map in Polymer 2

### ISSUE THREAD

**Issue by ameykshirsagar** [PolymerVis/mapbox-gl#3]
Hi,
I get a blank map in Polymer 2 when using as per your given steps.
What can I do to fix it??

**Comment by eterna2** [comment]
I have not migrated it to Polymer 2.
Polymer 2 has quite abit of changes, that will need significant time for me to migrate.

**Comment by jparish3** [comment]
this element is great. I hope the upgrade to 2.0 is underway. Is it possible to expose other map components...for example getting the map bounds coordinates:
var sw = new mapboxgl.LngLat(-73.9876, 40.7661);
var ne = new mapboxgl.LngLat(-73.9397, 40.8002);
var llb = new mapboxgl.LngLatBounds(sw, ne);

**Comment by eterna2** [comment]
Hi, 

I have upgrade to Polymer2.0.
Note this is a pure Polymer2.0. Not a hybrid aka it does not support legacy Polymer1.8.

There are some minor changes in the attributes because of the stricter type check for Polymer2.
You no longer can enter either URL or actual JSON for the source-data or map-style attributes. You now have to use `source-url` or `source-data` for URL or JSON respectively. Same goes for `map-style` and `map-style-url`.

Also added the ability to listen to either `mapbox-gl` itself or any of the `mapbox-layer`.

You can achieve your aim of getting the map boundaries by doing this via a callback.

The codes below show how u can get the bound everytime to click on the maplayer.

HTML
```html
            <mapbox-gl
                interactive
                access-token="[[key]]"
                map="{{map}}"
                zoom=10>
              </mapbox-gl>

              <mapbox-layer
                map="[[map]]"
                layer-id="coastline_outline"
                rendering-type="line"
                source="geojsonsrc"
                color="#eee"
                line-width=2></mapbox-layer>

              <mapbox-layer
                map="[[map]]"
                layer-id="coastline_fill"
                rendering-type="fill"
                source="geojsonsrc"
                color="#009688"
                opacity=0.7
                events-to-watch="click"
                on-mapbox-layer-click="handleClick"></mapbox-layer>

              <geojson-source
                map="[[map]]"
                source-id="geojsonsrc"
                source-url="./sg.geojson"></geojson-source>
``` 

Javascript
```javascript
var autobind = document.querySelector('dom-bind');

autobind.handleClick = function() {
    alert(autobind.map.getBounds())
};
```

**Comment by jparish3** [comment]
Hi:
Thanks for the upgrade to 2.0. I would like to use some of the map features
such as bounds for dynamic data-binding to API queries. I have implemented
a few approaches to use the  Mapbox API (see below) and the calls work for
an initial value, but do not update with map moves. I tried adding the
listener, but get a warning that the listener method is not defined. Let me
know if you have any suggestions. Thanks
<dom-module id="test-mapbox">
<template>
<style is="custom-style">
:host {
display: block;
position: relative;
box-sizing: border-box;
--paper-icon-button-ink-color: var(--paper-blue-grey200);
--paper-input-ink-color: var(--paper-blue-grey200);
--iron-icon-fill-color: var(--paper-blue-grey200);
}
#map{
height:900px;
width:100%;
@apply(--layout-flex);
}
div.textbox {
background-color: #eee;
color: #444;
padding: 5px;
line-height: 20px;
width: 128px;
height: 20px;
border-radius: 5px;
text-align: center;
}
div.arrow-down {
margin-left: 60px;
width: 0;
height: 0;
border-left: 8px solid transparent;
border-right: 8px solid transparent;
border-top: 10px solid #eee;
}
mapbox-gl-marker.big_kitten {
background-image: url('https://placekitten.com/g/64/64');
border: 2px solid #eee;
border-radius: 50%;
padding: 0;
width: 64px;
height: 64px;
}

paper-material {
background-color: white;
margin: 24px;
padding: 16px;
height: 1220px;
}

</style>
<paper-material elevation="1">
<div fit flex>

<mapbox-gl id="map"
interactive
on-mapbox-gl-move="_computeBoundsRadius()"
map="{{map}}"
map-style-url="mapbox://styles/mapbox/dark-v9"
access-token="{{accessToken}}"
latitude="{{lat}}"
longitude="{{lng}}"
zoom=2></mapbox-gl>

<mapbox-layer
map="[[map]]"
layer-id="coastline_fill"
rendering-type="fill"
source="geojsonsrc"
color="#009688"
opacity=0.7></mapbox-layer>

<mapbox-layer
map="[[map]]"
layer-id="coastline_outline"
rendering-type="line"
source="geojsonsrc"
color="#eee"
line-width=2
events-to-watch="click"
on-mapbox-layer-click="handleClick"></mapbox-layer>

<geojson-source
map="[[map]]"
source-id="geojsonsrc"
source-url="../data/places.geojson"></geojson-source>
</div>

<paper-input id="bounds" type="text" label="Bounds" value="{{boundsRadius}}"
></paper-input>

<span>TEST:[[center]]</span>
</paper-material>




</template>
<script>
Polymer({
is: 'test-mapbox',

properties: {
accessToken: {
type: String,
value: 'XX',
notify: true
},
mapLayer: {
type: String,
value: 'mapbox://styles/mapbox/dark-v9',
notify: true
},

fill: {
type: String,
value: '#9BCBEA',
notify: true
},
map: {
type: Object,
observer: '_mapChanged'
},
lat: {
type: Object,
value: 35.228878,
notify: true
},
lng: {
type: Object,
value: -80.840521,
notify: true
},
center: {
type: Object,
computed: ' _fillInCenter(map)',
notify: true
},
boundsRadius: {
type: Object,
computed: '_computeBoundsRadius(map)',
notify: true
},
},
_fillInCenter: function(event) {
return this.map.getCenter();
},
_computeBoundsRadius: function(lng,lat) {
var ll = new mapboxgl.LngLat(this.lng,this.lat);
return ll.toBounds(100).toArray();
},

handleClick:function(e, features) {
if (features.length > 0) {
alert(features[0].properties.COSTAL_NAM);
}
}
});
</script>
</dom-module>






Joe Parish
SPATIALytx
704.458.4798
