### ISSUE TITLE
Layer events don't trigger when interactive layers in dom-repeat

### ISSUE THREAD

**Issue by ralexrdz** [PolymerVis/mapbox-gl#33]
Continuing with #32 bug

Thanks for the commit fixing that bug, but now, layer events don't get triggered

Here is example [repo](https://github.com/ralexrdz/mapbox-layers-bug) with new commit now triggering click events
How to reproduce
 1. click "show 2 green layers" button
 1. click any of the circles and look in browser inspector for log "_layerClicked" (don't know why is triggered 2 times, also)
 1. click "show 3 red layers" button
 1. click all red circles. Just one will throw in the log the "_layerClicked"

**Comment by eterna2** [comment]
@ralexrdz 
Hi, this time I really fixed it. 

You can see a gist @ http://bl.ocks.org/eterna2/0c4e0bc21a3c534c8c1fa11dd296d714
