### ISSUE TITLE
on map click

### ISSUE THREAD

**Issue by hirenpatel868** [PolymerVis/mapbox-gl#34]
how to get click event of mapbox-gl element? ... i want latitude and longitude when user clicks on map..

**Comment by eterna2** [comment]
@hirenpatel868 

U can reference https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/event-handling.html

Essential, u register the events u want to watch thru the `events-to-watch` property. And then handle the respective event `mapbox-gl-<event>`.

```html
<mapbox-gl
  interactive
  access-token="USE_UR_OWN_TOKEN"
  events-to-watch="click"
  on-mapbox-gl-click="handleClick">
</mapbox-gl>
```
