### ISSUE TITLE
add  navigation control and geo locate control on map

### ISSUE THREAD

**Issue by hirenpatel868** [PolymerVis/mapbox-gl#35]
how to add navigation control or geo locate control on map using this element.. as per native map

**Comment by eterna2** [comment]
Hi @hirenpatel868 

I have not build anything for the controls yet. U will need to do it the normal way.

```
map.addControl(new mapboxgl.NavigationControl());
```

The `map` object can the obtain from the `mapbox-gl` element itself. 

```
document.querySelector('mapbox-gl').map.addControl(new mapboxgl.NavigationControl());
```

I will add this feature in the next release.

**Comment by eterna2** [comment]
@hirenpatel868 

You can use [`mapbox-gl-control`](https://www.webcomponents.org/element/PolymerVis/mapbox-gl/elements/mapbox-gl-control).

The example can be seen here:
https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/controls.html

**Comment by hirenpatel868** [comment]
@eterna2 wow..!! its working now..after applying your suggestions..thank u so much..
Need more 1 help...how  to make this kind of map using mapbox-gl...i just want to make user explore only specific area on map..not at all..as u can see in image..attached. how to add overlay..as in picture.is it overlay or anything else?
![picture1](https://user-images.githubusercontent.com/10207745/37569921-396ecc26-2b0f-11e8-8087-bd89e7c69e5a.png)
