### ISSUE TITLE
remove marker

### ISSUE THREAD

**Issue by hirenpatel868** [PolymerVis/mapbox-gl#43]
i am adding dynamically marker on map using mapbox-gl and map-boxmarker element .now i want to remove marker dynamically based on some id tag or class ..so how it can be possible?

**Comment by eterna2** [comment]
@hirenpatel868 
U would probably want to use `template is="dom-if"` for a single marker, or `template is="dom-repeat` for multiple markers, to control which marker to add or remove.

Example
```html
<mapbox-gl>
  <template is="dom-repeat" items="[[arrayOfMarkerObjects]]" filter="someFilterFunc">
    <mapbox-gl-marker latitude="[[item.lat]]" longitude="[[item.lng]]"></mapbox-gl-marker>
  </template>
</mapbox-gl>
```
So u can just use `Polymer`'s API (e.g. this.pop("arrayOfMarkerObjects")) to manipulate `arrayOfMarkerObjects` or just use the `someFilterFunc` to filter out the `markers` u do not want to render. 

More on how to use `template is=dom-repeat` at [polymer docs](https://www.polymer-project.org/2.0/docs/devguide/templates#filtering-and-sorting-lists)

**Comment by eterna2** [comment]
Issue closed as there is no further response.
